### ISSUE TITLE
SCSS (Sass) with Autoprefixer

### ISSUE THREAD

**Issue by lffg** [RomainLanz/adonis-bundler#1]
Hey,

Before opening this issue, I did a brief research, but found nothing that could help me.
I'm a little new to Parcel, but I liked the idea of this package (adonis-bundler).

After playing around, I had a question:
Is it possible to compile SCSS and then run an autoprefixer?

**Comment by RomainLanz** [comment]
Hey @lffg,

You can easily use postCSS with this plugin.
Simply create the configuration file of PostCSS and it should use it.

Let me know if you have any issues.

**Comment by lffg** [comment]
Yeah, I am aware of that.
But can I use SASS with Autoprefixer?

Thanks. 😄

**Comment by lffg** [comment]
Whoops (sorry).

**Comment by RomainLanz** [comment]
Yes.

Setup autoprefixer with PostCSS and simply use SASS to do your CSS.
Do you struggle anywhere?
